### ISSUE TITLE
[FEATURE] Show wallet address

### ISSUE THREAD

**Issue by Drabuna** [bitcart/bitcart#338]
**Is your feature request related to a problem? Please describe.**
When I create a wallet, I expect to see the wallet address.
Instead, I see the wallet ID(which is not very useful internal info), and contract address, but I don't see the address of the wallet.
If I click on expand on any specific wallet I can see XPUB or something called "address", but is just a key phrase.
I think it will be super useful to show the actual wallet address there.

**Describe the solution you'd like**
I want to be able to see the wallet address.

**Describe alternatives you've considered**
To find out what is the address of the wallet, I have to create an invoice and then discover it there.

**Comment by MrNaif2018** [comment]
Which network is it? For eth-based networks (tron too), the address is entered in the xpub field, and you can view it in details indeed
Maybe you created a hot wallet, then it's a private key
We can't probably? just show address because some wallets may have many addresses.
You may take a look at RPC plugin: https://github.com/bitcartcc/bitcart-plugins/tree/master/rpc-plugin where you can call getaddress function to get the address
